pageInfo:
  title: Ledger dev
  description: DevTools
  footerText: ''
  logo: >-
    https://enterprise.ledger.com/wp-content/uploads/2022/06/ledger_entreprise-white-1-1.png
sections:
  - name: Repo & Monitoring
    icon: fas fa-code
    displayData:
      sortBy: default
      sectionLayout: grid
      itemCountX: 5
      cols: 2
    items:
      - title: Github
        description: Main repos
        icon: favicon
        url: https://github.com/LedgerHQ
        id: 0_1570_github
      - title: Sonar
        description: Quality and complexity checking
        icon: favicon
        url: https://sonarcloud.io/organizations/ledger/projects
        id: 1_1570_sonar
      - title: Datadog - Staging
        icon: >-
          https://imgix.datadoghq.com/img/dd_logo_n_70x75.png?ch=Width,DPR&fit=max&auto=format&w=70&h=75
        url: https://ledgerstg.datadoghq.eu
        target: newtab
        id: 2_1570_datadogstaging
      - title: Datadog - Sandbox
        icon: >-
          https://imgix.datadoghq.com/img/dd_logo_n_70x75.png?ch=Width,DPR&fit=max&auto=format&w=70&h=75
        url: https://ledgersbx.datadoghq.eu/
        id: 3_1570_datadogsandbox
      - title: Datadog - Prod
        icon: >-
          https://imgix.datadoghq.com/img/dd_logo_n_70x75.png?ch=Width,DPR&fit=max&auto=format&w=70&h=75
        url: https://app.datadoghq.eu/
        id: 4_1570_datadogprod
  - name: Project Management
    icon: fas fa-analytics
    items:
      - title: Jira
        url: https://ledgerhq.atlassian.net/jira/your-work
        icon: favicon
        id: 0_1780_jira
      - title: Confluence
        url: https://ledgerhq.atlassian.net/wiki/home
        icon: favicon
        id: 1_1780_confluence
      - title: Miro
        url: https://miro.com/
        icon: favicon
        id: 2_1780_miro
  - name: Architecture Tools
    icon: fas fa-code
    displayData:
      sortBy: default
      sectionLayout: grid
      itemCountX: 5
      cols: 2
    items:
      - title: Excalidraw
        description: Excalidraw is a virtual collaborative whiteboard tool
        icon: favicon
        url: https://excalidraw.com/
        id: 0_1812_excalidraw
      - title: Lucid
        description: Lucidchart is the intelligent diagramming
        icon: favicon
        url: https://lucid.app/
        id: 1_1812_lucid
  - name: UI / UX
    icon: fas fa-analytics
    displayData:
      hideForUsers:
        - alicia
      sortBy: most-used
    items:
      - title: StoryBook
        description: Preview B2B
        url: >-
          https://ledgerhq.github.io/ledger-vault-front/?path=/story/vault-introduction--page
        icon: favicon
        id: 0_442_storybook
      - title: Figma
        description: Collaborative interface design tool
        url: https://www.figma.com/
        icon: favicon
        id: 1_442_figma
  - name: Registry
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Helm Chart - dev
        icon: >-
          https://cncf-branding.netlify.app/img/projects/helm/horizontal/color/helm-horizontal-color.png
        url: https://charts-dev.infra.ldg-prd.net/
        id: 0_857_helmchartdev
      - title: Helm chart
        icon: >-
          https://cncf-branding.netlify.app/img/projects/helm/horizontal/color/helm-horizontal-color.png
        url: https://charts.infra.ldg-prd.net/
        tags:
          - prod
        id: 1_857_helmchart
      - title: Nexus - Green
        icon: >-
          https://fr.sonatype.com/hubfs/Repo%20Combined%20Manager/Repo%20Icon%20with%20green.png
        url: https://nexus.green.ledgerlabs.net/
        id: 2_857_nexusgreen
      - title: Nexus - Orange
        icon: >-
          https://fr.sonatype.com/hubfs/Repo%20Combined%20Manager/Repo%20Icon%20with%20green.png
        url: https://nexus.orange.ledgerlabs.net/
        id: 3_857_nexusorange
  - name: Internal Tools
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Vault Remote
        icon: >-
          https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/emaa9ysgghoxko8ixeyu
        url: https://remote.minivault.ledger-sbx.com/
        id: 0_1390_vaultremote
      - title: Vault Guide
        icon: >-
          https://thumbs.dreamstime.com/b/documents-icon-trendy-documents-logo-concept-white-backgroun-documents-icon-trendy-documents-logo-concept-white-background-131173398.jpg
        url: https://vault-guide.ldg-tech.com/
        id: 1_1390_vaultguide
  - name: Deployment
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Spinnaker
        icon: >-
          https://cd.foundation/wp-content/uploads/sites/78/2020/04/spinnaker-icon-color-768x718.png
        url: https://spinnaker.infra.ldg-prd.net/
        id: 0_1057_spinnaker
      - title: LaunchDarkly
        description: Feature Flag
        icon: https://avatars.githubusercontent.com/u/8039656?s=200&v=4
        url: >-
          https://accounts.google.com/o/saml2/initsso?idpid=C030x4pai&spid=819823003122&forceauthn=false
        id: 1_1057_launchdarkly
pages:
  - name: Dev Tools
    path: dev.yml
  - name: Ledger Life
    path: common.yml
  - name: Crypto Dashboard
    path: crypto.yml
  - name: test
    path: test.yml
